# Introduction

Use dataset of airline arrival information to predict how late flights
will be. A flight only counts as late if it is more than 30 minutes late.  
(I cannot get the data in the Data expo ‘09 site, so I got data from this link https://www.kaggle.com/vikalpdongre/us-flights-data-2008 instead)

# Data exploration

In [1]:
import pandas as pd
from sklearn.utils import shuffle

In [2]:
data  = pd.read_csv('2008.csv')

data.shape

(7009728, 29)

There are over 7 million rows in the data files.

In [3]:
pd.set_option('display.max_columns', 0)

data.head(20)

    Year  Month  DayofMonth  ...  NASDelay  SecurityDelay  LateAircraftDelay
0   2008      1           3  ...       NaN            NaN                NaN
1   2008      1           3  ...       NaN            NaN                NaN
2   2008      1           3  ...       NaN            NaN                NaN
3   2008      1           3  ...       NaN            NaN                NaN
4   2008      1           3  ...       0.0            0.0               32.0
5   2008      1           3  ...       NaN            NaN                NaN
6   2008      1           3  ...       0.0            0.0               47.0
7   2008      1           3  ...       NaN            NaN                NaN
8   2008      1           3  ...       NaN            NaN                NaN
9   2008      1           3  ...       NaN            NaN                NaN
10  2008      1           3  ...       NaN            NaN                NaN
11  2008      1           3  ...       0.0            0.0               72.0
12  2008      1           3  ...       NaN            NaN                NaN
13  2008      1           3  ...       NaN            NaN                NaN
14  2008      1           3  ...       NaN            NaN                NaN
15  2008      1           3  ...       NaN            NaN                NaN
16  2008      1           3  ...       0.0            0.0               12.0
17  2008      1           3  ...       NaN            NaN                NaN
18  2008      1           3  ...       0.0            0.0               16.0
19  2008      1           3  ...       0.0            0.0               25.0

[20 rows x 29 columns]

Above is an example of data

And we need to check how many duplicated cells

In [ ]:
data.describe()

In [ ]:
data.info()

With this data, we see that there are 3 catergorical:
1. UniqueCarrier
2. TailNum
3. Origin
4. Dest
5. CancellationCode

In [ ]:
data.isnull().sum()

**CarrierDelay, WeatherDelay, NASDelay, SecurityDelay, LateAircraftDelay** fields have over 5 million missing data  
Nearly all rows miss **CancellationCode** data

In [ ]:
data.isnull().mean() * 100

Above is the percentage of missing data

In [ ]:
data.CancellationCode.unique()

Because there are alot of null data in **CancellationCode** collumn, we shows CancellationCode data to see if its importance  
We write that unavailable data in **CancellationCode** will be another type of value: **0**

In [ ]:
data['CancellationCode'] = data['CancellationCode'].fillna(0)

In [ ]:
data.isnull().mean() * 100

Now we do not have null value in **CancellationCode**, we do this because **CancellationCode** is categorical field  
We will do this with **TailNum and Origin**

In [ ]:
data['TailNum'] = data['TailNum'].fillna(0)
data['Origin'] = data['Origin'].fillna(0)

In [ ]:
data.isnull().mean() * 100

In [ ]:
data.TailNum.unique().size

As TailNum fields has too many fields, we break it down to 3 different fields **TailNumLetter**, **TailNum**, **TailNumCode**.  

Example:  **N712SW**  
-> TailNumLetter: **N**  
-> TailNum: **712**  
-> TailNumCode: **SW**

In [ ]:
# extract 2 last letters in TailNum as it may describe a certain flight code
def extract_2_last_letter(s):
    s = str(s)
    return s[-2:]

def extract_3_mid_number(s):
    s = str(s)
    return s[1:4]

def extract_1st_letter(s):
    s = str(s)
    return s[:1]

data['TailNumLetter'] = data.TailNum.apply(extract_1st_letter)
data['TailNumCode'] = data.TailNum.apply(extract_2_last_letter)
data['TailNum'] = data.TailNum.apply(extract_3_mid_number)

print (data[['TailNumLetter', 'TailNum', 'TailNumCode']].head())